targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          include:
            - lib/screens/create_challenge/models/create_challenge_response.dart
      injectable_generator:injectable_config_builder:
        enabled: true
        generate_for:
          include:
            - lib/screens/create_challenge/models/create_challenge_response.dart
      freezed:freezed:
        enabled: true
        generate_for:
          include:
            - lib/screens/create_challenge/models/create_challenge_response.dart
