// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX3_6qUGwcaRIYIevbfj_4kTf_eMHs9EI',
    appId: '1:897448131657:web:0bfb899d481dd3fcc7d398',
    messagingSenderId: '897448131657',
    projectId: 'skillspe-d376e',
    authDomain: 'skillspe-d376e.firebaseapp.com',
    storageBucket: 'skillspe-d376e.appspot.com',
    measurementId: 'G-699TF12B4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlzXbgTuKJOYgmFv2xEIo0hwRM0QvNYWo',
    appId: '1:897448131657:android:3f7442da6b9f0822c7d398',
    messagingSenderId: '897448131657',
    projectId: 'skillspe-d376e',
    storageBucket: 'skillspe-d376e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw1hSNtfgI9e_AnSuZIO9BfbfupFE5JWg',
    appId: '1:897448131657:ios:57601683ca7f219dc7d398',
    messagingSenderId: '897448131657',
    projectId: 'skillspe-d376e',
    storageBucket: 'skillspe-d376e.appspot.com',
    iosBundleId: 'com.example.skillsPe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw1hSNtfgI9e_AnSuZIO9BfbfupFE5JWg',
    appId: '1:897448131657:ios:a4d890676cf1d9f7c7d398',
    messagingSenderId: '897448131657',
    projectId: 'skillspe-d376e',
    storageBucket: 'skillspe-d376e.appspot.com',
    iosBundleId: 'com.example.skillsPe.RunnerTests',
  );
}
